version: "3"
services:
  smsc:
    build:
      context: smsc
    ports:
      - "127.0.0.1:9000:88"
  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    ports:
      - "127.0.0.1:9005:15672"
  redis:
    image: redis:alpine
  redis-browser:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=redis
    ports:
      - "127.0.0.1:9010:8081"
    depends_on:
      - redis
  vumi-t:
    build:
      context: vumi/transport
    environment:
      - AMQP_HOST=rabbitmq
      - REDIS_HOST=redis
    depends_on:
      - smsc
      - rabbitmq
      - redis
  vumi-r:
    build:
      context: vumi/http_relay
    environment:
      - AMQP_HOST=rabbitmq
      - REDIS_HOST=redis
    depends_on:
      - vumi-t
  app:
    build:
      context: app
    depends_on:
      - vumi-r
